server:
  port: 8300
  servlet:
    context-path: /cafe
spring:
  application:
    name: cafe-ordering-system
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://abee.pub:3306/cafe?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: password
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
